# Generated by Django 4.1.5 on 2024-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_equipment_bookings_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='ultraconcurrent',
            field=models.BooleanField(default=False),
        ),
    ]
